### ISSUE TITLE
uninitialized constant ActiveGraph::Config (NameError)

### ISSUE THREAD

**Issue by namiwang** [neo4jrb/activegraph#1595]
# repro

1. create a blank new rails app
2. add `gem 'activegraph', github: 'neo4jrb/activegraph', branch: 'master'` in Gemfile and bundle (which is commit #e387298980351d67029274b696c4672434d1f51a)
3. add `require 'active_graph/railtie'` in `application.rb`

# unexpected behavior

```
/Users/nami/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant': uninitialized constant ActiveGraph::Config (NameError)
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
	from /Users/nami/.rvm/gems/ruby-2.7.0/bundler/gems/activegraph-e38729898035/lib/active_graph/railtie.rb:51:in `block in <class:Railtie>'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `run'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `each'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `call'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/railties-6.0.2.2/lib/rails/application.rb:363:in `initialize!'
	from /Users/nami/workspace/the_npm_game/the_npm_game/config/environment.rb:5:in `<main>'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/spring-2.1.0/lib/spring/application.rb:106:in `preload'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	from /Users/nami/.rvm/gems/ruby-2.7.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /Users/nami/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'

```

**Comment by klobuczek** [comment]
@namiwang I was able to bypass the issue by adding:
```
require 'active_graph'
```
to `application.rb`. I cannot explain the reason. It works on our rails app (5.2.3) without it. If you find out please let me know.
BTW you don't need to use the activegraph gem from github source. Any significant change is immediately pushed to rubygems.org as beta version.

**Comment by namiwang** [comment]
@klobuczek Thanks for the response.

I got another error `cannot load such file -- neo4j_ruby_driver`, After added `require 'active_garph'`.

I guess it's all somehow related to the new loading mechanics introduced in rails 6.

**Comment by mhanberg** [comment]
I saw this same error, and when adding the call to `require 'active_graph'`, I am now seeing a zeitwerk error about ActiveModel

```
/Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require': cannot load such file -- active_model/attribute_set (LoadError)
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/activegraph-10.0.0.pre.beta.3/lib/active_graph/lazy_attribute_hash.rb:1:in `<top (required)>'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/activegraph-10.0.0.pre.beta.3/lib/active_graph.rb:18:in `<top (required)>'
        from /Users/mitchellhanberg/Development/socialgraphapi/config/application.rb:8:in `require'
        from /Users/mitchellhanberg/Development/socialgraphapi/config/application.rb:8:in `<top (required)>'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/mitchellhanberg/.asdf/installs/ruby/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from -e:1:in `<main>'
```

**Comment by mhanberg** [comment]
I may have solved it locally, but we have since re-written this service in Elixir. Sorry, wish I could offer more help 😕.

**Comment by jacek213** [comment]
No worries, thanks the feedback :+1: 

@klobuczek maybe you'd be able to help? I'm trying to migrate from 9.x to 10. I see that activemodel is locked at `>= 4.0` for this gem and I'm currently running v5.1.6.

**Comment by cknoxrun** [comment]
Also chasing this problem trying to migrate. I have a Rails 6 branch in the works (same codebase), where this error doesn't occur, so I imagine it is a Rails 5.1 (possibly 5.2) issue.

**Comment by nomasprime** [comment]
After spending almost two days reinstalling various versions of Ruby and Rails to try and get various Neo4J gems to work, I can state that Neo4J does not love Ruby 😆

**Comment by pmackay** [comment]
I would also appreciate some guidance on this issue.
