### ISSUE TITLE
Unable to start test db with new ActiveGraph gem due to seabolt error

### ISSUE THREAD

**Issue by hraynaud** [neo4jrb/activegraph#1619]
Hi I'm Mac OS 10.15.6 and on ruby 2.6.3

I tried upgrading from neo4jrb 9.2.0 to activegraph 10.0.1 after following the upgrade instructions when I try to start the test or development database I get this error stack trace.

rake aborted!
LoadError: Could not open library 'libseabolt17': dlopen(libseabolt17, 5): image not found.
Could not open library 'libseabolt17.dylib': dlopen(libseabolt17.dylib, 5): image not found
/Users/herbyraynaud/Code/personal/konmego/vendor/bundle/ruby/2.6.0/gems/ffi-1.13.1/lib/ffi/library.rb:145:in `block in ffi_lib'
/Users/herbyraynaud/Code/personal/konmego/vendor/bundle/ruby/2.6.0/gems/ffi-1.13.1/lib/ffi/library.rb:99:in `map'
/Users/herbyraynaud/Code/personal/konmego/vendor/bundle/ruby/2.6.0/gems/ffi-1.13.1/lib/ffi/library.rb:99:in `ffi_lib'
/Users/herbyraynaud/Code/personal/konmego/vendor/bundle/ruby/2.6.0/gems/neo4j-ruby-driver-1.7.0/ffi/bolt/library.rb:9:in `extended'
/Users/herbyraynaud/Code/personal/konmego/vendor/bundle/ruby/2.6.0/gems/neo4j-ruby-driver-1.7.0/ffi/bolt/address_resolver.rb:5:in `extend'
/Users/herbyraynaud/Code/personal/konmego/vendor/bundle/ruby/2.6.0/gems/neo4j-ruby-driver-1.7.0/ffi/bolt/address_resolver.rb:5:in `<module:AddressResolver>'
/Users/herbyraynaud/Code/personal/konmego/vendor/bundle/ruby/2.6.0/gems/neo4j-ruby-driver-1.7.0/ffi/bolt/address_resolver.rb:4:in `<module:Bolt>'

I've tried to install the seabolt driver via homebrew as recommended in the doc like so:
brew install michael-simons/homebrew-seabolt/seabolt

While that appears to work i'm still unable to get the app running. When I create a fresh app according to the setup instructions I get a similar error as seen below.

rails aborted!
LoadError: Could not open library 'libseabolt17': dlopen(libseabolt17, 5): image not found.
Could not open library 'libseabolt17.dylib': dlopen(libseabolt17.dylib, 5): image not found
/Users/herbyraynaud/Code/personal/myapp/config/application.rb:18:in `<main>'
/Users/herbyraynaud/Code/personal/myapp/Rakefile:4:in `<main>'
/Users/herbyraynaud/Code/personal/myapp/bin/rails:9:in `<top (required)>'
/Users/herbyraynaud/Code/personal/myapp/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)

**Comment by hraynaud** [comment]
Actually I was able to resolve this. I had to manually copy the seabolt files from the directory where homebrew installed them to the /usr/local/lib directory. Thanks.
